doodle:
  usepad: true
  internalPadUrl: "http://api-etherpad-1:9001/"
  externalPadUrl: "http://api-etherpad-1:9001/"
  padApiKey: "19d89ca52bc0fa4f19d6325464d9d7a032649b9fa68c111514627081e2784b4a"
  organizermail: "olivier.barais@gmail.com"
  tmpfolder: "/tmp/excelFiles"
quarkus:
  datasource:
    db-kind: mysql
    username: tlc
    password: tlc
    jdbc:
      url: jdbc:mysql://api-db-1:3306/tlc?useUnicode=true&serverTimezone=Europe/Paris
      driver: com.mysql.cj.jdbc.Driver
  flyway:
    migrate-at-start: true
    baseline-on-migrate: true
#    database:
#      generation: none
#      globally-quoted-identifiers: true
  mailer:
    from: test@quarkus.io
#    host: smtp.sendgrid.net
    host: api-mail-1
    port: 2525
#    port: 465
#    ssl: true

#    username: ""
#    password: ""
    mock: false
